{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8085
      name: {{ .Values.service.portName }}
  selector:
    {{- include "cc.selectorLabels" . | nindent 4 }}
{{- end }}
